Exit:ESCAPE
Jump :SPACE #comment
Help: h 
# just a commment
 Action : CONTROL#comment after

 Only first:
 Single value

Three:values : hehe
ReloadConfig: c
Up: UP
Down: DOWN
Left: LEFT
Right: RIGHT
NudgeLeft: COMMA 
NudgeRight: PERIOD
Restart: r
