# FPS cap for the game
# 1000 leads to 1ms frame time, and therefore lower input processing latencies
# Note that the configured Keyboard polling rate still affects input latency
TargetFps: 500
# Set to false to use the fallback audio api by default
UseAsio:    true
# Name of the driver to choose (in case of multiple installed)
# If empty the first entry is chosen
AsioDriverName: Wine ASIO Other Driver 
# Size of the buffer, lower is better (lower latency)
# The buffersize needs to be supported by the asio driver
# Setting only applies when ASIO is used
AudioBufferSize: 256 # anotehr comment
# Volume value between 0 and 
# Reference is -60db at 0 | -30db at 0.5 | -3db at 1
   MasterVolume   : 0.35
Master volume 2  :

